name: MonoFaceCompute
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.8, <3.9
  - pytorch=1.12.1=py3.8_cuda11.6_cudnn8.3.2_0
  - torchvision=0.13.1
  - librosa=0.9.2
  - loguru=0.6.0
  - onnx=1.10.2
  - onnx2torch=1.5
  - pandas=1.4.2
  - pip~=23.3
  - pyrender=0.1.45
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scikit-video=1.1.11
  - imgaug==0.4.0
  - omegaconf~=2.0
  - hickle==5.0.2
  - munch==2.5.0
  - pyyaml~=6.0
  - tqdm=4.66.5
  - Cython~=0.29
  - imageio=2.33.1
  - pip:
    - albumentations==1.0.3
    - compress-pickle==1.2.0
    - chumpy==0.70
    - face-alignment==1.3.4
    - facenet-pytorch==2.5.2
    - gdown==4.5.1
    - insightface==0.6.2
    - matplotlib==3.2.2
    - numpy==1.23.0
    - onnxruntime-gpu==1.19.2
    - opencv-python-headless==4.9.0.80
    - pytorch-lightning==1.4.9
    - torchmetrics==0.6.2
    - torchfile==0.1.0
    - transformers==4.22.2
    - trimesh==3.6.43
    - wandb~=0.10
    - face-detection-tflite==0.6.0
    - timm==0.9.16